### ISSUE TITLE
automate rendering of meta-project files & configuration via cmake

### ISSUE THREAD

**Issue by cvirtue** [cvirtue/salvador#14]
- [x] `.modules` -> `.cmake`
- [x] `.cmake/configurable`
  - [x] `dox.configuration.in`
  - [x] `readme.md.in`
    - [x]  to have the `project version` set
- [x] `.cmake/Configurables.cmake`
- [x] `SANITIZE` -> `Sanitize`
- [x] (install) `compile_commands.json` (to `${PROJECT_SOURCE_DIR}`)
- [x] adjust `renderer`s (in `salvador`) for new `layout`
- [x] add `renderer` for 
  - [x] `.cmake/configurables/dox.configuration.in`
  - [x] `.cmake/configurables/readme.md.in`
  - [x] `.cmake/Configurables.cmake`
- [x] refine `salvador` `blackbox` testing
  - [x] expect `.in` files to be rendered
  - [x] expect target files to be rendered from `.in` files on `cmake ..`
